import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { AppModule } from './app/app.module';
import { addIcons } from 'ionicons';
import { 
  personOutline, 
  peopleOutline, 
  listOutline, 
  logOutOutline, 
  cameraOutline, 
  searchOutline, 
  notificationsOutline, 
  closeCircleOutline, 
  close, 
  home, 
  warningOutline, 
  checkmarkCircleOutline, 
  checkmarkDoneOutline, 
  timeOutline, 
  alertCircleOutline, 
  arrowUndoOutline, 
  arrowBackOutline,
  cameraReverseOutline,
  arrowForwardOutline,
  cubeOutline,
  terminalOutline,
  addOutline,
  search,
  menuOutline,
  businessOutline,
  shieldOutline,
  playOutline,
  playForwardOutline,
  trashOutline,
  addCircleOutline,
  closeCircle,
  chevronForwardOutline,
  chevronDownOutline,
  chevronUpOutline,
  helpCircleOutline,
  personAddOutline,
  mailOutline,
  ribbonOutline
} from 'ionicons/icons';

// Register all icons used across the app
addIcons({
  'person-outline': personOutline,
  'people-outline': peopleOutline,
  'list-outline': listOutline,
  'log-out-outline': logOutOutline,
  'camera-outline': cameraOutline,
  'search-outline': searchOutline,
  'notifications-outline': notificationsOutline,
  'close-circle-outline': closeCircleOutline,
  'close': close,
  'home': home,
  'warning-outline': warningOutline,
  'checkmark-circle-outline': checkmarkCircleOutline,
  'checkmark-done-outline': checkmarkDoneOutline,
  'time-outline': timeOutline,
  'alert-circle-outline': alertCircleOutline,
  'arrow-undo-outline': arrowUndoOutline,
  'arrow-back-outline': arrowBackOutline,
  'camera-reverse-outline': cameraReverseOutline,
  'arrow-forward-outline': arrowForwardOutline,
  'cube-outline': cubeOutline,
  'terminal-outline': terminalOutline,
  'add-outline': addOutline,
  'search': search,
  'menu-outline': menuOutline,
  'business-outline': businessOutline,
  'shield-outline': shieldOutline,
  'play-outline': playOutline,
  'play-forward-outline': playForwardOutline,
  'trash-outline': trashOutline,
  'add-circle-outline': addCircleOutline,
  'close-circle': closeCircle,
  'chevron-forward-outline': chevronForwardOutline,
  'chevron-down-outline': chevronDownOutline,
  'chevron-up-outline': chevronUpOutline,
  'help-circle-outline': helpCircleOutline,
  'person-add-outline': personAddOutline,
  'mail-outline': mailOutline,
  'ribbon-outline': ribbonOutline
});

platformBrowserDynamic().bootstrapModule(AppModule)
  .catch(err => console.log(err));
